FROM python:3.8

USER root
RUN apt-get update
RUN apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
RUN apt-get install -y ffmpeg
RUN apt-get install -y build-essential git curl

# Install from conda env
RUN pip install \
        'numpy<=1.21.1' \
        pandas \
        scipy \
        scikit-learn \
        statsmodels \
        ipympl \
        ipykernel \
        tqdm \
        librosa \
        pyyaml \
        jupyterlab \
        seaborn \
        openpyxl \
        xlwt \
        opencv-contrib-python \
        'scikit-image>=0.18' \
        imutils \
        pysimplegui \
        pykalman \
        mediapipe \
        tgt \
        setuptools


RUN mkdir mipcat
RUN mkdir mipcat/Devel
RUN cd /mipcat/Devel

RUN git clone https://github.com/goiosunsw/timeseries
RUN git clone https://github.com/goiosunsw/pypevoc
RUN git clone https://github.com/goiosunsw/mipcat

RUN cd /mipcat/Devel/timeseries
RUN pip install -e .
RUN cd /mipcat/Devel/pypevoc
RUN pip install -e .
RUN cd /mipcat/Devel/mipcat
RUN pip install -e .

EXPOSE 8888

#CMD cd ${MAIN_PATH} && sh run_jupyterlab.sh
CMD /bin/bash
