{% set version = "0.1.0" %}
{% set name = "mipcat" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../


requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - scipy
    - numpy
    - python
    - pandas
    - opencv
    - scikit-learn
    - QtPy
    - librosa
    - ipykernel
    - jupyterlab
    - matplotlib
    - scipy
    - statsmodels
    - tqdm


about:
  home: "https://github.com/goiosunsw/mipcat.git"
  license: "GNU Lesser General Public v3 or later (LGPLv3+)"
  license_family: "LGPL"
  license_file: ""
  summary: "Musical Instrument Performance Capture and Analysis Toolbox"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - goiosunsw
